<?php

namespace Database\Seeders;

use App\Models\Item;
use App\Models\ProductPrice;
use Illuminate\Database\Seeder;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            // ================= PROSTHETICS =================
            [
                'branch_id' => 1,
                'name' => 'Dental Crown',
                'description' => 'Tooth cap',
                'category' => 'prosthetics',
                'width' => 1.5,
                'height' => 1.0,
                'depth' => 1.5,
                'is_sterile' => true,
                'expire_date' => null,
                'materials' => ['Porcelain'],
                'track_stock' => false,
                'requires_batch' => false,
                'requires_expiry' => false,
                'is_consumable' => false,
            ],
            [
                'branch_id' => 1,
                'name' => 'Dental Bridge',
                'description' => 'Replace missing teeth',
                'category' => 'prosthetics',
                'width' => 2.0,
                'height' => 1.2,
                'depth' => 1.8,
                'is_sterile' => true,
                'expire_date' => null,
                'materials' => ['Ceramic'],
                'track_stock' => false,
                'requires_batch' => false,
                'requires_expiry' => false,
                'is_consumable' => false,
            ],
            [
                'branch_id' => 1,
                'name' => 'Implant Fixture',
                'description' => 'Implant base',
                'category' => 'prosthetics',
                'width' => 0.5,
                'height' => 1.5,
                'depth' => 0.5,
                'is_sterile' => true,
                'expire_date' => now()->addYears(2)->toDateString(),
                'materials' => ['Titanium'],
                'track_stock' => true,
                'requires_batch' => true,
                'requires_expiry' => true,
                'is_consumable' => true,
            ],
            [
                'branch_id' => 1,
                'name' => 'Denture',
                'description' => 'Removable teeth',
                'category' => 'prosthetics',
                'width' => 3.0,
                'height' => 2.0,
                'depth' => 2.5,
                'is_sterile' => true,
                'expire_date' => null,
                'materials' => ['Acrylic'],
                'track_stock' => false,
                'requires_batch' => false,
                'requires_expiry' => false,
                'is_consumable' => false,
            ],
            [
                'branch_id' => 1,
                'name' => 'Veneer',
                'description' => 'Cosmetic tooth covering',
                'category' => 'prosthetics',
                'width' => 1.0,
                'height' => 0.8,
                'depth' => 1.2,
                'is_sterile' => true,
                'expire_date' => null,
                'materials' => ['Porcelain', 'Composite'],
                'track_stock' => false,
                'requires_batch' => false,
                'requires_expiry' => false,
                'is_consumable' => false,
            ],

            // ================= DEVICES =================
            [
                'branch_id' => 1,
                'name' => 'Dental Chair',
                'description' => 'Patient chair',
                'category' => 'devices',
                'width' => 60.0,
                'height' => 120.0,
                'depth' => 80.0,
                'is_sterile' => false,
                'expire_date' => null,
                'materials' => ['Metal', 'Leather'],
                'track_stock' => false,
                'requires_batch' => false,
                'requires_expiry' => false,
                'is_consumable' => false,
            ],
            [
                'branch_id' => 1,
                'name' => 'Compressor',
                'description' => 'Air supply',
                'category' => 'devices',
                'width' => 40.0,
                'height' => 80.0,
                'depth' => 30.0,
                'is_sterile' => false,
                'expire_date' => null,
                'materials' => ['Metal'],
                'track_stock' => false,
                'requires_batch' => false,
                'requires_expiry' => false,
                'is_consumable' => false,
            ],
            [
                'branch_id' => 1,
                'name' => 'Autoclave',
                'description' => 'Sterilizer',
                'category' => 'devices',
                'width' => 50.0,
                'height' => 70.0,
                'depth' => 40.0,
                'is_sterile' => false,
                'expire_date' => null,
                'materials' => ['Steel'],
                'track_stock' => false,
                'requires_batch' => false,
                'requires_expiry' => false,
                'is_consumable' => false,
            ],
            [
                'branch_id' => 1,
                'name' => 'Ultrasonic Cleaner',
                'description' => 'Instrument cleaning',
                'category' => 'devices',
                'width' => 25.0,
                'height' => 20.0,
                'depth' => 20.0,
                'is_sterile' => false,
                'expire_date' => null,
                'materials' => ['Metal'],
                'track_stock' => false,
                'requires_batch' => false,
                'requires_expiry' => false,
                'is_consumable' => false,
            ],
            [
                'branch_id' => 1,
                'name' => 'X-Ray Unit',
                'description' => 'Digital x-ray machine',
                'category' => 'devices',
                'width' => 100.0,
                'height' => 150.0,
                'depth' => 50.0,
                'is_sterile' => false,
                'expire_date' => null,
                'materials' => ['Metal', 'Plastic'],
                'track_stock' => false,
                'requires_batch' => false,
                'requires_expiry' => false,
                'is_consumable' => false,
            ],

            // ================= FURNITURE =================
            [
                'branch_id' => 1,
                'name' => 'Dental Cabinet',
                'description' => 'Storage',
                'category' => 'furniture',
                'width' => 80.0,
                'height' => 180.0,
                'depth' => 40.0,
                'is_sterile' => false,
                'expire_date' => null,
                'materials' => ['Wood'],
                'track_stock' => false,
                'requires_batch' => false,
                'requires_expiry' => false,
                'is_consumable' => false,
            ],
            [
                'branch_id' => 1,
                'name' => 'Dentist Stool',
                'description' => 'Doctor seating',
                'category' => 'furniture',
                'width' => 50.0,
                'height' => 80.0,
                'depth' => 50.0,
                'is_sterile' => false,
                'expire_date' => null,
                'materials' => ['Metal', 'Foam'],
                'track_stock' => false,
                'requires_batch' => false,
                'requires_expiry' => false,
                'is_consumable' => false,
            ],
            [
                'branch_id' => 1,
                'name' => 'Patient Waiting Chair',
                'description' => 'Reception seating',
                'category' => 'furniture',
                'width' => 60.0,
                'height' => 90.0,
                'depth' => 70.0,
                'is_sterile' => false,
                'expire_date' => null,
                'materials' => ['Metal', 'Fabric'],
                'track_stock' => false,
                'requires_batch' => false,
                'requires_expiry' => false,
                'is_consumable' => false,
            ],
            [
                'branch_id' => 1,
                'name' => 'Reception Desk',
                'description' => 'Front desk',
                'category' => 'furniture',
                'width' => 150.0,
                'height' => 100.0,
                'depth' => 60.0,
                'is_sterile' => false,
                'expire_date' => null,
                'materials' => ['Wood', 'Glass'],
                'track_stock' => false,
                'requires_batch' => false,
                'requires_expiry' => false,
                'is_consumable' => false,
            ],
            [
                'branch_id' => 1,
                'name' => 'Instrument Tray',
                'description' => 'Sterile tray for tools',
                'category' => 'furniture',
                'width' => 30.0,
                'height' => 5.0,
                'depth' => 20.0,
                'is_sterile' => true,
                'expire_date' => null,
                'materials' => ['Steel'],
                'track_stock' => false,
                'requires_batch' => false,
                'requires_expiry' => false,
                'is_consumable' => false,
            ],

            // ================= INSTRUMENTS =================
            [
                'branch_id' => 1,
                'name' => 'Mouth Mirror',
                'description' => 'Oral examination',
                'category' => 'instruments',
                'width' => 2.0,
                'height' => 15.0,
                'depth' => 1.0,
                'is_sterile' => true,
                'expire_date' => null,
                'materials' => ['Steel'],
                'track_stock' => true,
                'requires_batch' => false,
                'requires_expiry' => false,
                'is_consumable' => false,
            ],
            [
                'branch_id' => 1,
                'name' => 'Explorer Probe',
                'description' => 'Detect decay',
                'category' => 'instruments',
                'width' => 1.0,
                'height' => 18.0,
                'depth' => 0.5,
                'is_sterile' => true,
                'expire_date' => null,
                'materials' => ['Steel'],
                'track_stock' => true,
                'requires_batch' => false,
                'requires_expiry' => false,
                'is_consumable' => false,
            ],
            [
                'branch_id' => 1,
                'name' => 'Cotton Pliers',
                'description' => 'Handle materials',
                'category' => 'instruments',
                'width' => 3.0,
                'height' => 12.0,
                'depth' => 2.0,
                'is_sterile' => true,
                'expire_date' => null,
                'materials' => ['Steel'],
                'track_stock' => true,
                'requires_batch' => false,
                'requires_expiry' => false,
                'is_consumable' => false,
            ],
            [
                'branch_id' => 1,
                'name' => 'Scaler',
                'description' => 'Remove calculus',
                'category' => 'instruments',
                'width' => 2.5,
                'height' => 16.0,
                'depth' => 1.5,
                'is_sterile' => true,
                'expire_date' => null,
                'materials' => ['Steel'],
                'track_stock' => true,
                'requires_batch' => false,
                'requires_expiry' => false,
                'is_consumable' => false,
            ],
            [
                'branch_id' => 1,
                'name' => 'Curette',
                'description' => 'Periodontal cleaning',
                'category' => 'instruments',
                'width' => 2.0,
                'height' => 17.0,
                'depth' => 1.0,
                'is_sterile' => true,
                'expire_date' => null,
                'materials' => ['Steel'],
                'track_stock' => true,
                'requires_batch' => false,
                'requires_expiry' => false,
                'is_consumable' => false,
            ],

            // ================= MEDICATIONS =================
            [
                'branch_id' => 1,
                'name' => 'Lidocaine Cartridge',
                'description' => 'Local anesthetic',
                'category' => 'medications',
                'width' => 2.0,
                'height' => 4.0,
                'depth' => 2.0,
                'is_sterile' => true,
                'expire_date' => now()->addYears(1)->toDateString(),
                'materials' => ['Liquid'],
                'track_stock' => true,
                'requires_batch' => true,
                'requires_expiry' => true,
                'is_consumable' => true,
            ],
            [
                'branch_id' => 1,
                'name' => 'Ibuprofen Tablets',
                'description' => 'Pain relief',
                'category' => 'medications',
                'width' => 5.0,
                'height' => 10.0,
                'depth' => 5.0,
                'is_sterile' => false,
                'expire_date' => now()->addYears(2)->toDateString(),
                'materials' => ['Tablet'],
                'track_stock' => true,
                'requires_batch' => true,
                'requires_expiry' => true,
                'is_consumable' => true,
            ],
            [
                'branch_id' => 1,
                'name' => 'Amoxicillin Capsules',
                'description' => 'Antibiotic',
                'category' => 'medications',
                'width' => 4.0,
                'height' => 8.0,
                'depth' => 4.0,
                'is_sterile' => false,
                'expire_date' => now()->addYears(1)->toDateString(),
                'materials' => ['Capsule'],
                'track_stock' => true,
                'requires_batch' => true,
                'requires_expiry' => true,
                'is_consumable' => true,
            ],
            [
                'branch_id' => 1,
                'name' => 'Chlorhexidine Mouthwash',
                'description' => 'Antiseptic rinse',
                'category' => 'medications',
                'width' => 8.0,
                'height' => 20.0,
                'depth' => 8.0,
                'is_sterile' => false,
                'expire_date' => now()->addYears(1)->toDateString(),
                'materials' => ['Liquid'],
                'track_stock' => true,
                'requires_batch' => true,
                'requires_expiry' => true,
                'is_consumable' => true,
            ],
            [
                'branch_id' => 1,
                'name' => 'Fluoride Gel',
                'description' => 'Tooth strengthening',
                'category' => 'medications',
                'width' => 6.0,
                'height' => 15.0,
                'depth' => 6.0,
                'is_sterile' => false,
                'expire_date' => now()->addYears(1)->toDateString(),
                'materials' => ['Gel'],
                'track_stock' => true,
                'requires_batch' => true,
                'requires_expiry' => true,
                'is_consumable' => true,
            ],

            // ================= CONSUMABLES =================
            [
                'branch_id' => 1,
                'name' => 'Gloves',
                'description' => 'Hand protection',
                'category' => 'consumables',
                'width' => 10.0,
                'height' => 20.0,
                'depth' => 5.0,
                'is_sterile' => true,
                'expire_date' => now()->addYears(2)->toDateString(),
                'materials' => ['Latex'],
                'track_stock' => true,
                'requires_batch' => false,
                'requires_expiry' => true,
                'is_consumable' => true,
            ],
            [
                'branch_id' => 1,
                'name' => 'Face Mask',
                'description' => 'Air protection',
                'category' => 'consumables',
                'width' => 15.0,
                'height' => 10.0,
                'depth' => 1.0,
                'is_sterile' => false,
                'expire_date' => now()->addYears(1)->toDateString(),
                'materials' => ['Fabric'],
                'track_stock' => true,
                'requires_batch' => false,
                'requires_expiry' => true,
                'is_consumable' => true,
            ],
            [
                'branch_id' => 1,
                'name' => 'Cotton Rolls',
                'description' => 'Moisture control',
                'category' => 'consumables',
                'width' => 3.0,
                'height' => 3.0,
                'depth' => 3.0,
                'is_sterile' => true,
                'expire_date' => null,
                'materials' => ['Cotton'],
                'track_stock' => true,
                'requires_batch' => false,
                'requires_expiry' => false,
                'is_consumable' => true,
            ],
            [
                'branch_id' => 1,
                'name' => 'Gauze Pads',
                'description' => 'Wound care',
                'category' => 'consumables',
                'width' => 10.0,
                'height' => 10.0,
                'depth' => 2.0,
                'is_sterile' => true,
                'expire_date' => null,
                'materials' => ['Cotton'],
                'track_stock' => true,
                'requires_batch' => false,
                'requires_expiry' => false,
                'is_consumable' => true,
            ],
            [
                'branch_id' => 1,
                'name' => 'Suction Tips',
                'description' => 'Fluid suction',
                'category' => 'consumables',
                'width' => 1.0,
                'height' => 5.0,
                'depth' => 1.0,
                'is_sterile' => true,
                'expire_date' => null,
                'materials' => ['Plastic'],
                'track_stock' => true,
                'requires_batch' => false,
                'requires_expiry' => false,
                'is_consumable' => true,
            ],
        ];

        foreach ($items as $itemData) {
            $item = Item::create($itemData);

            // Create a base price for each item
            $priceMap = [
                'prosthetics' => [150, 500],
                'devices' => [500, 15000],
                'furniture' => [200, 3000],
                'instruments' => [20, 150],
                'medications' => [5, 50],
                'consumables' => [2, 30],
            ];

            $range = $priceMap[$item->category] ?? [10, 100];
            $price = rand($range[0], $range[1]) + 0.99;

            ProductPrice::create([
                'pricable_id' => $item->id,
                'pricable_type' => Item::class,
                'price' => $price,
                'effective_from' => now(),
                'is_active' => true,
            ]);
        }
    }
}
